// Code generated by go run ./internal/platform/protocol/gen. DO NOT EDIT.

export interface Message<T = unknown> {
  type: MessageType;
  payload?: T;
}

export const MsgTypes = {
  // ── 平台 ──
  /** 断线重连 */
  MsgReconnect: 'reconnect',
  /** 心跳 ping */
  MsgPing: 'ping',
  /** 创建房间 */
  MsgCreateRoom: 'create_room',
  /** 加入房间 */
  MsgJoinRoom: 'join_room',
  /** 离开房间 */
  MsgLeaveRoom: 'leave_room',
  /** 关闭房间（仅房主可操作） */
  MsgCloseRoom: 'close_room',
  /** 快速匹配 */
  MsgQuickMatch: 'quick_match',
  /** 取消匹配 */
  MsgCancelMatch: 'cancel_match',
  /** 人机练习（创建带 2 个机器人席位的房间） */
  MsgPracticeMatch: 'practice_match',
  /** 添加机器人（手动占用房间空席位） */
  MsgAddBot: 'add_bot',
  /** 关闭已有房间并新建（单请求完成，仅房主可用） */
  MsgRecreateRoom: 'recreate_room',
  /** 准备就绪 */
  MsgReady: 'ready',
  /** 取消准备 */
  MsgCancelReady: 'cancel_ready',
  /** 离开对局（客户端 UI 离开对战页面时通知服务端终止） */
  MsgLeaveGame: 'leave_game',
  /** 获取个人统计 */
  MsgGetStats: 'get_stats',
  /** 获取排行榜 */
  MsgGetLeaderboard: 'get_leaderboard',
  /** 获取房间列表 */
  MsgGetRoomList: 'get_room_list',
  /** 获取在线人数 */
  MsgGetOnlineCount: 'get_online_count',
  /** 获取维护状态 */
  MsgGetMaintenanceStatus: 'get_maintenance_status',
  /** 更新玩家资料 */
  MsgUpdateProfile: 'update_profile',
  /** 更新复盘功能设置 */
  MsgUpdateReplaySetting: 'update_replay_setting',
  /** 对局同步检测（客户端主动查询） */
  MsgGameSync: 'game_sync',
  /** 请求对局状态（场景恢复用） */
  MsgRequestGameState: 'request_game_state',
  /** 清理用户数据（房间+对战） */
  MsgClearUserData: 'clear_user_data',
  /** 连接成功 */
  MsgConnected: 'connected',
  /** 重连成功 */
  MsgReconnected: 'reconnected',
  /** 心跳 pong */
  MsgPong: 'pong',
  /** 玩家掉线通知 */
  MsgPlayerOffline: 'player_offline',
  /** 玩家上线通知 */
  MsgPlayerOnline: 'player_online',
  /** 在线人数更新 */
  MsgOnlineCount: 'online_count',
  /** 房间创建成功 */
  MsgRoomCreated: 'room_created',
  /** 加入房间成功 */
  MsgRoomJoined: 'room_joined',
  /** 其他玩家加入 */
  MsgPlayerJoined: 'player_joined',
  /** 玩家离开 */
  MsgPlayerLeft: 'player_left',
  /** 玩家准备 */
  MsgPlayerReady: 'player_ready',
  /** 匹配成功 */
  MsgMatchFound: 'match_found',
  /** 游戏开始（通用：玩家列表 + 房间选项） */
  MsgGameStart: 'game_start',
  /** 游戏结束（通用：胜者 + 得分 + 游戏扩展数据） */
  MsgGameOver: 'game_over',
  /** 个人统计结果 */
  MsgStatsResult: 'stats_result',
  /** 排行榜结果 */
  MsgLeaderboardResult: 'leaderboard_result',
  /** 房间列表结果 */
  MsgRoomListResult: 'room_list_result',
  /** 主动推送 */
  MsgMaintenancePush: 'maintenance_push',
  /** 被动拉取 */
  MsgMaintenancePull: 'maintenance_pull',
  /** 错误消息 */
  MsgError: 'error',
  /** 资料更新通知 */
  MsgProfileUpdated: 'profile_updated',
  /** 复盘功能设置更新通知 */
  MsgReplaySettingUpdated: 'replay_setting_updated',
  /** 对局同步检测结果 */
  MsgGameSyncResult: 'game_sync_result',
  /** 对局状态响应（请求状态恢复） */
  MsgGameState: 'game_state',
  /** 用户数据清理完成通知 */
  MsgUserDataCleared: 'user_data_cleared',
  // ── 游戏: chess ──
  /** 走子 */
  MsgCcMove: 'cc_move',
  /** 挂机/取消挂机 */
  MsgCcAfk: 'cc_afk',
  /** 认输 */
  MsgCcResign: 'cc_resign',
  /** 请求和棋 */
  MsgCcDrawRequest: 'cc_draw_request',
  /** 和棋应答 */
  MsgCcDrawResponse: 'cc_draw_response',
  /** 轮到走子 */
  MsgCcTurn: 'cc_turn',
  /** 有人走子 */
  MsgCcMoveMade: 'cc_move_made',
  /** 挂机状态变更通知 */
  MsgCcAfkChanged: 'cc_afk_changed',
  /** 对手请求和棋通知 */
  MsgCcDrawRequested: 'cc_draw_requested',
  /** 和棋请求结果 */
  MsgCcDrawResult: 'cc_draw_result',
  // ── 游戏: ddz ──
  /** 叫分（1/2/3 分） */
  MsgBid: 'bid',
  /** 加倍 */
  MsgDouble: 'double',
  /** 出牌 */
  MsgPlayCards: 'play_cards',
  /** 不出 */
  MsgPass: 'pass',
  /** 挂机/取消挂机（托管开关） */
  MsgAfk: 'afk',
  /** 发牌 */
  MsgDealCards: 'deal_cards',
  /** 轮到叫分 / 加倍 */
  MsgBidTurn: 'bid_turn',
  /** 叫分 / 加倍结果 */
  MsgBidResult: 'bid_result',
  /** 地主确定 */
  MsgLandlord: 'landlord',
  /** 轮到出牌 */
  MsgPlayTurn: 'play_turn',
  /** 挂机状态变更通知 */
  MsgAfkChanged: 'afk_changed',
  /** 有人出牌 */
  MsgCardPlayed: 'card_played',
  /** 有人不出 */
  MsgPlayerPass: 'player_pass',
  // ── 游戏: gomoku ──
  /** 落子 */
  MsgGkMove: 'gk_move',
  /** 挂机/取消挂机（托管开关） */
  MsgGkAfk: 'gk_afk',
  /** 认输 */
  MsgGkResign: 'gk_resign',
  /** 请求和棋 */
  MsgGkDrawRequest: 'gk_draw_request',
  /** 和棋应答 */
  MsgGkDrawResponse: 'gk_draw_response',
  /** 轮到落子 */
  MsgGkTurn: 'gk_turn',
  /** 有人落子 */
  MsgGkMoveMade: 'gk_move_made',
  /** 挂机状态变更通知 */
  MsgGkAfkChanged: 'gk_afk_changed',
  /** 对手请求和棋通知 */
  MsgGkDrawRequested: 'gk_draw_requested',
  /** 和棋请求结果 */
  MsgGkDrawResult: 'gk_draw_result',
  // ── 游戏: mahjong ──
  /** 出牌 */
  MsgMjDiscard: 'mj_discard',
  /** 挂机/取消挂机 */
  MsgMjAfk: 'mj_afk',
  /** 碰 */
  MsgMjPong: 'mj_pong',
  /** 杠（明杠） */
  MsgMjKong: 'mj_kong',
  /** 胡（自摸/点炮） */
  MsgMjWin: 'mj_win',
  /** 放弃碰/杠/胡 */
  MsgMjPass: 'mj_pass',
  /** 轮到出牌 */
  MsgMjTurn: 'mj_turn',
  /** 玩家摸牌（仅通知该玩家） */
  MsgMjDraw: 'mj_draw',
  /** 有人出牌 */
  MsgMjDiscarded: 'mj_discarded',
  /** 有人碰牌 */
  MsgMjPongMade: 'mj_pong_made',
  /** 有人杠牌 */
  MsgMjKongMade: 'mj_kong_made',
  /** 可碰/杠/胡，请选择 */
  MsgMjActionAvail: 'mj_action_avail',
  /** 挂机状态变更 */
  MsgMjAfkChanged: 'mj_afk_changed',
  /** 牌墙已尽，流局 */
  MsgMjWallEmpty: 'mj_wall_empty',
  /** 开局掷骰定庄（广播） */
  MsgMjDice: 'mj_dice',
} as const;

export type MessageType = (typeof MsgTypes)[keyof typeof MsgTypes];

/** AddBotPayload 手动向房间空席位添加机器人请求 */
export interface AddBotPayload {
  /** 机器人难度 normal=正常/hard=专家，默认 normal（难度只影响机器人记牌完整度） */
  difficulty?: string;
}

/** AfkChangedPayload 挂机状态变更通知（广播给全房间） */
export interface AfkChangedPayload {
  player_id: string;
  afk: boolean;
}

/** AfkPayload 挂机请求（托管开关：挂机后由机器人策略自动决策） */
export interface AfkPayload {
  /** true = 挂机, false = 取消挂机 */
  afk: boolean;
}

/** BidPayload 叫分请求 */
export interface BidPayload {
  /** 0 = 不叫, 1/2/3 = 叫分（须大于当前最高分） */
  score: number;
}

/** BidResultPayload 叫分 / 加倍结果通知 */
export interface BidResultPayload {
  player_id: string;
  player_name: string;
  /** call=叫分阶段, double=加倍阶段 */
  phase: string;
  /** 叫分阶段所叫分数（0=不叫） */
  score: number;
  /** 加倍阶段是否加倍 */
  double: boolean;
  /** 决策后的当前倍数 */
  multiplier: number;
}

/** BidTurnPayload 轮到叫分 / 加倍通知 */
export interface BidTurnPayload {
  player_id: string;
  /** 超时时间（秒） */
  timeout: number;
  /** call=叫分阶段, double=加倍阶段 */
  phase: string;
  /** 叫分阶段当前最高分（0=尚无人叫） */
  high_bid: number;
  /** 当前倍数 */
  multiplier: number;
}

/** CardInfo 牌信息 */
export interface CardInfo {
  /** 花色: 0=黑桃, 1=红心, 2=梅花, 3=方块, 4=王 */
  suit: number;
  /** 点数: 3-17 (3-2, 小王=16, 大王=17) */
  rank: number;
  /** 颜色: 0=黑, 1=红 */
  color: number;
}

/** CardPlayedPayload 出牌通知 */
export interface CardPlayedPayload {
  player_id: string;
  player_name: string;
  cards: CardInfo[];
  /** 剩余手牌数 */
  cards_left: number;
  /** 牌型名称 */
  hand_type: string;
}

/** CcAfkChangedPayload 挂机状态变更通知 */
export interface CcAfkChangedPayload {
  player_id: string;
  afk: boolean;
}

/** CcAfkPayload 挂机请求 */
export interface CcAfkPayload {
  afk: boolean;
}

/** CcDrawRequestPayload 和棋请求 */
export interface CcDrawRequestPayload {
  /** 请求者 playerID */
  requester_id: string;
}

/** CcDrawRequestedPayload 通知对手有人请求和棋 */
export interface CcDrawRequestedPayload {
  requester_id: string;
  requester_name: string;
}

/** CcDrawResponsePayload 和棋应答 */
export interface CcDrawResponsePayload {
  /** true=同意和棋, false=拒绝 */
  accept: boolean;
}

/** CcDrawResultPayload 和棋请求结果 */
export interface CcDrawResultPayload {
  /** true=双方同意和棋（对局已结束）, false=被拒绝 */
  accepted: boolean;
}

/** CcGameStateDTO 游戏状态数据传输对象（重连恢复用） */
export interface CcGameStateDTO {
  /** playing/ended */
  phase: string;
  players: PlayerInfo[];
  /** 9×10 行优先 */
  board: number[];
  current_turn: string;
  /** 该 DTO 视角玩家阵营（1=红, 2=黑） */
  my_camp: number;
  /** 最近一手起点（-1 = 尚未走子） */
  last_from_row: number;
  last_from_col: number;
  last_to_row: number;
  last_to_col: number;
  move_number: number;
  /** 红方吃掉的棋子 */
  red_captures: number[];
  /** 黑方吃掉的棋子 */
  black_captures: number[];
}

/** CcMoveMadePayload 走子通知 */
export interface CcMoveMadePayload {
  player_id: string;
  player_name: string;
  from_row: number;
  from_col: number;
  to_row: number;
  to_col: number;
  /** 走动的棋子 */
  piece: number;
  /** 被吃的棋子（0 = 无） */
  captured: number;
  move_number: number;
}

/** CcMovePayload 走子请求 */
export interface CcMovePayload {
  from_row: number;
  from_col: number;
  to_row: number;
  to_col: number;
}

/** CcResignPayload 认输请求（空结构） */
export interface CcResignPayload {
}

/** CcTurnPayload 轮到走子通知 */
export interface CcTurnPayload {
  player_id: string;
  /** 1=红, 2=黑 */
  camp: number;
  /** 超时时间（秒） */
  timeout: number;
  /** 本局第几手（1 起） */
  move_number: number;
}

/** ConnectedPayload 连接成功响应 */
export interface ConnectedPayload {
  player_id: string;
  player_name: string;
  /** 重连令牌 */
  reconnect_token: string;
  /** 当前积分 */
  score: number;
  /** 当前排名（0 = 未上榜） */
  rank: number;
}

/** CreateRoomPayload 创建房间请求（缺省 game_id 兼容为 "ddz"） */
export interface CreateRoomPayload {
  /** 游戏 ID（如 "ddz"） */
  game_id?: string;
}

/** DealCardsPayload 发牌通知 */
export interface DealCardsPayload {
  /** 玩家自己的手牌 */
  cards: CardInfo[];
  /** 底牌（地主确定后才显示具体内容） */
  bottom_cards: CardInfo[];
}

/** DoublePayload 加倍请求（地主确定后的加倍阶段） */
export interface DoublePayload {
  /** true = 加倍, false = 不加倍 */
  double: boolean;
}

/** ErrorPayload 错误响应 */
export interface ErrorPayload {
  code: number;
  message: string;
  /** 可选额外数据（如 ErrRoomExists 时的房间信息） */
  data?: unknown;
}

/** GameOverExtra 斗地主 game_over 扩展数据（放入平台 GameOverPayload.Extra） */
export interface GameOverExtra {
  /** 所有玩家剩余手牌 */
  player_hands: PlayerHand[];
  /** 最终倍数 */
  multiplier: number;
}

/** GameOverPayload 游戏结束通知（平台级通用信封；游戏私有数据放 Extra） */
export interface GameOverPayload {
  winner_id: string;
  winner_name: string;
  /** 和棋原因（平局时可选，如 repetition/natural_limit/insufficient_material） */
  draw_reason?: string;
  /** 每位玩家本局得分 */
  scores: PlayerScore[];
  /** 游戏扩展数据（斗地主：剩余手牌/倍数） */
  extra?: unknown;
}

/** GameStartPayload 游戏开始通知（平台级通用信封） */
export interface GameStartPayload {
  /** 按座位顺序排列 */
  players: PlayerInfo[];
  /** 房间选项（如斗地主 difficulty=normal/hard） */
  options?: unknown;
}

/** GameStateDTO 游戏状态数据传输对象（重连恢复用） */
export interface GameStateDTO {
  /** bidding/doubling/playing */
  phase: string;
  /** 所有玩家信息 */
  players: PlayerInfo[];
  /** 自己的手牌 */
  hand: CardInfo[];
  /** 底牌 */
  bottom_cards: CardInfo[];
  /** 当前回合玩家 ID */
  current_turn: string;
  /** 上家出的牌 */
  last_played: CardInfo[];
  /** 上家 ID */
  last_player_id: string;
  /** 是否必须出牌 */
  must_play: boolean;
  /** 是否能打过 */
  can_beat: boolean;
  /** 当前倍数 */
  multiplier: number;
}

/** GameStatePayload 对局状态响应（服务端 → 客户端；State 为游戏私有状态 JSON） */
export interface GameStatePayload {
  /** 是否有活跃对局 */
  available: boolean;
  /** 游戏私有状态（斗地主：GameStateDTO） */
  state?: unknown;
}

/** GameSyncResultPayload 对局同步检测结果（服务端 → 客户端） */
export interface GameSyncResultPayload {
  /** active=对局进行中 | waiting=房间等待中 | none=无房间 */
  status: string;
  /** 房间号（status != none 时返回） */
  room_code?: string;
}

/** GetLeaderboardPayload 获取排行榜请求 */
export interface GetLeaderboardPayload {
  /** 游戏（空按缺省游戏） */
  game_id?: string;
  /** total/daily/weekly */
  type: string;
  /** 偏移量 */
  offset: number;
  /** 数量 */
  limit: number;
}

/** GetRoomListPayload 获取房间列表请求（缺省 game_id 兼容为 "ddz"） */
export interface GetRoomListPayload {
  /** 按游戏过滤房间列表 */
  game_id?: string;
}

/** GetStatsPayload 获取个人战绩请求（payload 可缺省，空按缺省游戏） */
export interface GetStatsPayload {
  game_id?: string;
}

/** GkAfkChangedPayload 挂机状态变更通知（广播给全房间） */
export interface GkAfkChangedPayload {
  player_id: string;
  afk: boolean;
}

/** GkAfkPayload 挂机请求（托管开关：挂机后由机器人策略自动落子） */
export interface GkAfkPayload {
  /** true = 挂机, false = 取消挂机 */
  afk: boolean;
}

/** GkDrawRequestPayload 和棋请求 */
export interface GkDrawRequestPayload {
  /** 请求者 playerID */
  requester_id: string;
}

/** GkDrawRequestedPayload 通知对手有人请求和棋 */
export interface GkDrawRequestedPayload {
  requester_id: string;
  requester_name: string;
}

/** GkDrawResponsePayload 和棋应答 */
export interface GkDrawResponsePayload {
  /** true=同意和棋, false=拒绝 */
  accept: boolean;
}

/** GkDrawResultPayload 和棋请求结果 */
export interface GkDrawResultPayload {
  /** true=双方同意和棋（对局已结束）, false=被拒绝 */
  accepted: boolean;
}

/** GkGameStateDTO 游戏状态数据传输对象（重连恢复用） */
export interface GkGameStateDTO {
  /** playing/ended */
  phase: string;
  players: PlayerInfo[];
  /** 15×15 行优先：0=空, 1=黑, 2=白 */
  board: number[];
  current_turn: string;
  /** 该 DTO 视角玩家执子颜色（1=黑, 2=白） */
  my_color: number;
  /** 最近一手位置（-1 = 尚未落子） */
  last_row: number;
  last_col: number;
  /** 下一手的序号（1 起） */
  move_number: number;
}

/** GkMoveMadePayload 落子通知 */
export interface GkMoveMadePayload {
  player_id: string;
  player_name: string;
  row: number;
  col: number;
  /** 1=黑, 2=白 */
  color: number;
  /** 本局第几手（1 起） */
  move_number: number;
}

/** GkMovePayload 落子请求 */
export interface GkMovePayload {
  /** 行（0-14） */
  row: number;
  /** 列（0-14） */
  col: number;
}

/** GkResignPayload 认输请求（空结构） */
export interface GkResignPayload {
}

/** GkTurnPayload 轮到落子通知 */
export interface GkTurnPayload {
  player_id: string;
  /** 超时时间（秒） */
  timeout: number;
  /** 本局第几手（1 起） */
  move_number: number;
}

/** JoinRoomPayload 加入房间请求 */
export interface JoinRoomPayload {
  room_code: string;
}

/** LandlordPayload 地主确定通知 */
export interface LandlordPayload {
  player_id: string;
  player_name: string;
  /** 底牌 */
  bottom_cards: CardInfo[];
  /** 底倍（叫分确定的分数） */
  multiplier: number;
}

/** LeaderboardEntry 排行榜条目 */
export interface LeaderboardEntry {
  rank: number;
  player_id: string;
  player_name: string;
  score: number;
  wins: number;
  win_rate: number;
}

/** LeaderboardResultPayload 排行榜结果 */
export interface LeaderboardResultPayload {
  /** total/daily/weekly */
  type: string;
  entries: LeaderboardEntry[];
}

/** LeaveGamePayload 离开对局请求（客户端 UI 离开对战页面时发送，服务端终止对局） */
export interface LeaveGamePayload {
}

/** MaintenancePayload 维护模式通知 */
export interface MaintenancePayload {
  /** 是否在维护模式 */
  maintenance: boolean;
}

/** MaintenanceStatusPayload 维护状态响应 */
export interface MaintenanceStatusPayload {
  /** 是否在维护模式 */
  maintenance: boolean;
}

/** MjActionAvailPayload 可用动作通知（定向） */
export interface MjActionAvailPayload {
  can_pong: boolean;
  can_kong: boolean;
  can_win: boolean;
  /** 相关牌 */
  tile: number;
  timeout: number;
}

/** MjAfkChangedPayload 挂机状态变更 */
export interface MjAfkChangedPayload {
  player_id: string;
  afk: boolean;
}

/** MjAfkPayload 挂机请求 */
export interface MjAfkPayload {
  afk: boolean;
}

/** MjDicePayload 开局掷骰结果（广播） */
export interface MjDicePayload {
  /** 各玩家掷骰点数（与 players 索引对齐） */
  values: number[];
  /** 庄家索引（先手） */
  dealer: number;
}

/** MjDiscardPayload 出牌请求 */
export interface MjDiscardPayload {
  /** 牌类型（0-33） */
  tile: number;
}

/** MjDiscardedPayload 出牌通知（广播） */
export interface MjDiscardedPayload {
  player_id: string;
  tile: number;
}

/** MjDrawPayload 摸牌通知（定向发给摸牌玩家） */
export interface MjDrawPayload {
  /** 摸到的牌 */
  tile: number;
  /** 剩余牌数 */
  wall_remain: number;
}

/** MjGameStateDTO 游戏状态（重连恢复用） */
export interface MjGameStateDTO {
  /** playing/ended */
  phase: string;
  players: MjPlayerHandDTO[];
  current_turn: string;
  /** 自己在 players 中的索引 */
  my_index: number;
  /** 庄家座位 */
  dealer: number;
  wall_remain: number;
  meld_number: number;
  /** 每个玩家的弃牌池 */
  discard_pools: number[][];
}

/** MjKongMadePayload 杠牌通知（广播） */
export interface MjKongMadePayload {
  player_id: string;
  tile: number;
  /** 被杠的玩家 ID（暗杠/补杠时为空） */
  from: string;
  /** 是否暗杠 */
  is_ankong: boolean;
  /** 是否补杠（碰后加杠，客户端将已碰面子升级为杠） */
  is_add_kong: boolean;
}

/** MjKongPayload 杠请求 */
export interface MjKongPayload {
  /** 要杠的牌 */
  tile: number;
}

/** MjMeldDTO 面子信息 */
export interface MjMeldDTO {
  /** 0=碰 1=杠 3=暗杠 */
  type: number;
  tile: number;
  /** 来源玩家座位 */
  from: number;
}

/** MjPassPayload 放弃动作 */
export interface MjPassPayload {
}

/** MjPlayerHandDTO 玩家手牌信息（对其他玩家隐藏具体牌面） */
export interface MjPlayerHandDTO {
  player_id: string;
  player_name: string;
  seat: number;
  is_bot: boolean;
  online: boolean;
  afk: boolean;
  /** 手牌数量（对其他玩家可见） */
  hand_count: number;
  /** 仅自己可见 */
  hand?: number[];
  melds: MjMeldDTO[];
  is_dealer: boolean;
  /** 玩家平台积分（头像下方展示） */
  score: number;
}

/** MjPongMadePayload 碰牌通知（广播） */
export interface MjPongMadePayload {
  player_id: string;
  tile: number;
  /** 被碰的玩家 ID */
  from: string;
}

/** MjPongPayload 碰请求 */
export interface MjPongPayload {
  /** 要碰的牌 */
  tile: number;
}

/** MjTurnPayload 轮到出牌通知 */
export interface MjTurnPayload {
  player_id: string;
  timeout: number;
  /** 本局第几巡（1 起） */
  meld_number: number;
}

/** MjWinPayload 胡请求 */
export interface MjWinPayload {
  /** true=自摸, false=点炮 */
  is_self_draw: boolean;
}

/** OnlineCountPayload 在线人数更新 */
export interface OnlineCountPayload {
  /** 当前在线人数 */
  count: number;
}

/** PingPayload 心跳请求 */
export interface PingPayload {
  /** 客户端时间戳（毫秒） */
  timestamp: number;
}

/** PlayCardsPayload 出牌请求 */
export interface PlayCardsPayload {
  cards: CardInfo[];
}

/** PlayTurnPayload 轮到出牌通知 */
export interface PlayTurnPayload {
  player_id: string;
  /** 超时时间（秒） */
  timeout: number;
  /** 是否必须出牌（新一轮开始时为 true） */
  must_play: boolean;
  /** 是否有牌能打过上家 */
  can_beat: boolean;
}

/** PlayerHand 玩家手牌信息（用于游戏结束展示） */
export interface PlayerHand {
  player_id: string;
  player_name: string;
  cards: CardInfo[];
}

/** PlayerInfo 玩家信息 */
export interface PlayerInfo {
  id: string;
  name: string;
  /** 座位号 0-2 */
  seat: number;
  /** 是否准备 */
  ready: boolean;
  /** 是否是地主 */
  is_landlord: boolean;
  /** 手牌数量 */
  cards_count: number;
  /** 是否在线 */
  online: boolean;
  /** 是否是机器人 */
  is_bot?: boolean;
  /** 是否挂机（仅对局内有效） */
  afk?: boolean;
}

/** PlayerJoinedPayload 其他玩家加入通知 */
export interface PlayerJoinedPayload {
  player: PlayerInfo;
}

/** PlayerLeftPayload 玩家离开通知 */
export interface PlayerLeftPayload {
  player_id: string;
  player_name: string;
}

/** PlayerOfflinePayload 玩家掉线通知 */
export interface PlayerOfflinePayload {
  player_id: string;
  player_name: string;
  /** 等待重连超时（秒） */
  timeout: number;
}

/** PlayerOnlinePayload 玩家上线通知 */
export interface PlayerOnlinePayload {
  player_id: string;
  player_name: string;
}

/** PlayerPassPayload 不出通知 */
export interface PlayerPassPayload {
  player_id: string;
  player_name: string;
}

/** PlayerReadyPayload 玩家准备通知 */
export interface PlayerReadyPayload {
  player_id: string;
  ready: boolean;
}

/** PlayerScore 玩家本局得分（用于游戏结束结算） */
export interface PlayerScore {
  player_id: string;
  player_name: string;
  /** 是否是地主（斗地主专属） */
  is_landlord?: boolean;
  /** 本局得分（输为负，赢为正） */
  score: number;
}

/** PongPayload 心跳响应 */
export interface PongPayload {
  /** 客户端发送的时间戳 */
  client_timestamp: number;
  /** 服务器时间戳（毫秒） */
  server_timestamp: number;
}

/** PracticeMatchPayload 人机练习请求（缺省 game_id 兼容为 "ddz"） */
export interface PracticeMatchPayload {
  /** 游戏 ID */
  game_id?: string;
  /** 斗地主机器人难度 normal=正常/hard=专家，默认 normal（难度只影响机器人记牌完整度） */
  difficulty?: string;
}

/** ProfileUpdatedPayload 资料更新通知 */
export interface ProfileUpdatedPayload {
  player_id: string;
  /** 新昵称 */
  player_name: string;
}

/** QuickMatchPayload 快速匹配请求（缺省 game_id 兼容为 "ddz"） */
export interface QuickMatchPayload {
  /** 游戏 ID（按游戏分队列） */
  game_id?: string;
}

/** ReconnectPayload 断线重连请求 */
export interface ReconnectPayload {
  /** 重连令牌 */
  token: string;
  /** 玩家 ID */
  player_id: string;
}

/** ReconnectedPayload 重连成功响应 */
export interface ReconnectedPayload {
  player_id: string;
  player_name: string;
  /** 轮换后的新令牌 */
  reconnect_token: string;
  /** 如果在房间中 */
  room_code?: string;
  /** 如果在游戏中（游戏私有状态 JSON） */
  game_state?: unknown;
  /** 当前积分 */
  score: number;
  /** 当前排名（0 = 未上榜） */
  rank: number;
}

/** RecreateRoomPayload 关闭已有房间并新建请求（单请求完成关闭+新建并返回最终结果，仅房主可用） */
export interface RecreateRoomPayload {
  /** 新房间所属游戏 */
  game_id?: string;
  /** true=人机练习（机器人填满剩余席位） */
  practice?: boolean;
  /** 人机练习机器人难度 normal/hard */
  difficulty?: string;
}

/** ReplaySettingUpdatedPayload 复盘功能设置更新通知 */
export interface ReplaySettingUpdatedPayload {
  player_id: string;
  /** 复盘功能状态 */
  replay_enabled: boolean;
}

/** RoomCreatedPayload 房间创建成功响应 */
export interface RoomCreatedPayload {
  room_code: string;
  /** 房间所属游戏 */
  game_id: string;
  player: PlayerInfo;
}

/** RoomExistsData ErrRoomExists 错误的额外数据：已有房间的基本信息 */
export interface RoomExistsData {
  room_code: string;
  game_id: string;
  creator_is_self: boolean;
}

/** RoomJoinedPayload 加入房间成功响应 */
export interface RoomJoinedPayload {
  room_code: string;
  /** 房间所属游戏 */
  game_id?: string;
  /** 房间创建人（仅创建人可添加机器人） */
  creator_id?: string;
  player: PlayerInfo;
  /** 房间内所有玩家 */
  players: PlayerInfo[];
}

/** RoomListItem 房间列表项 */
export interface RoomListItem {
  room_code: string;
  /** 房间所属游戏 */
  game_id: string;
  player_count: number;
  max_players: number;
  /** 房间创建人昵称 */
  creator_name?: string;
  /** waiting=等待中 / playing=对局进行中 */
  state: string;
}

/** RoomListResultPayload 房间列表结果 */
export interface RoomListResultPayload {
  rooms: RoomListItem[];
}

/** StatsResultPayload 个人统计结果 */
export interface StatsResultPayload {
  player_id: string;
  player_name: string;
  total_games: number;
  wins: number;
  losses: number;
  win_rate: number;
  landlord_games: number;
  landlord_wins: number;
  farmer_games: number;
  farmer_wins: number;
  score: number;
  rank: number;
  current_streak: number;
  max_win_streak: number;
}

/** UpdateProfilePayload 更新玩家资料请求 */
export interface UpdateProfilePayload {
  /** 新昵称（1-20 字符） */
  name: string;
}

/** UpdateReplaySettingPayload 更新复盘功能设置请求 */
export interface UpdateReplaySettingPayload {
  /** 是否启用复盘功能 */
  replay_enabled: boolean;
}

/** UserDataClearedPayload 用户数据清理完成通知 */
export interface UserDataClearedPayload {
  player_id: string;
}

